# Felix's Dev Universe - Simple HTML GitHub Page

title: Felix's Dev Universe
description: Rust Developer | AI Enthusiast | Open Source Contributor

# 禁用 Jekyll 主题，使用纯 HTML
theme: null

# 基础URL配置
baseurl: ""
url: "https://felixx3001.github.io"

# 最小化排除列表
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - deploy.ps1
  - vendor/
  - .bundle/
  - .git/
  - .github/
